source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rack-cors"
gem "bcrypt", "~> 3.1"
gem "jwt"
gem "sidekiq", "~> 7.0"
gem "aws-sdk-s3", require: false
gem "image_processing", "~> 1.2"
gem "mini_magick", "~> 5.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "anthropic"
gem "httparty"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "faker"
  gem "dotenv-rails"
end

group :development do
  gem "spring"
end

group :test do
  gem "shoulda-matchers", "~> 5.0"
  gem "database_cleaner-active_record"
  gem "vcr"
  gem "webmock"
  gem "simplecov", require: false
end
